open http://loopinsight.com
open http://arstechnica.com
open http://www.techmeme.com/
open https://news.ycombinator.com/
open http://www.engadget.com/
open http://appleinsider.com
open http://9to5mac.com
open http://www.macstories.net
open http://themacobserver.com
open http://www.imore.com
open http://www.macdrifter.com
open https://www.apple.com/hotnews/
open http://daringfireball.net
open http://www.tuaw.com
open http://xkcd.com/
open http://techcrunch.com/
open http://recode.net/all-news/
open http://www.cnet.com/topics/security/
